[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cbor_metadata = true
ffi = true
optimizer = true
optimizer_runs = 1000_000
evm_version = "shanghai"
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]
fs_permissions = [{ access = "read-write", path = "./" }]

[profile.zksync]
src = 'src'
libs = ['lib']
fallback_oz = true
is_system = false
mode = "3"
cbor_metadata = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
gas_reports = ["*"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[etherscan]
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 57575762 }
