[profile.default]
src = "src"
out = "out"
libs = ["lib"]
cbor_metadata = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[etherscan]
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 57575762 }